[tool.poetry]
name = "taller-0"
version = "0.1.0"
description = ""
authors = ["ju4nsepulveda <juan.sepulveda.z@ab-inbev.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"